"""
SQLAlchemy database models for event storage and analytics.
"""

from datetime import datetime
from sqlalchemy import (
    Column,
    String,
    Integer,
    Float,
    Boolean,
    DateTime,
    ForeignKey,
    JSON,
    Index,
)
from sqlalchemy.orm import relationship

from app.database import Base


class EventRecord(Base):
    """
    Raw event storage table.

    Stores all visitor events generated by the CCTV pipeline.
    """

    __tablename__ = "event_records"

    event_id = Column(String, primary_key=True, unique=True, nullable=False)

    store_id = Column(String, nullable=False, index=True)
    camera_id = Column(String, nullable=False)

    visitor_id = Column(String, nullable=False, index=True)

    event_type = Column(String, nullable=False)

    timestamp = Column(DateTime, nullable=False, index=True)

    zone_id = Column(String, nullable=True)

    dwell_ms = Column(Integer, nullable=True)

    is_staff = Column(Boolean, default=False, nullable=False)

    confidence = Column(Float, nullable=True)

    metadata_json = Column(
    "metadata",
    JSON,
    nullable=True,
)

    created_at = Column(
        DateTime,
        default=datetime.utcnow,
        nullable=False
    )

    __table_args__ = (
        Index("idx_event_store_timestamp", "store_id", "timestamp"),
        Index("idx_event_visitor_timestamp", "visitor_id", "timestamp"),
    )


class VisitorSession(Base):
    """
    Aggregated visitor session information.

    Represents a complete store visit.
    """

    __tablename__ = "visitor_sessions"

    session_id = Column(
        String,
        primary_key=True,
        nullable=False
    )

    visitor_id = Column(
        String,
        nullable=False,
        index=True
    )

    store_id = Column(
        String,
        nullable=False,
        index=True
    )

    entry_time = Column(
        DateTime,
        nullable=False
    )

    exit_time = Column(
        DateTime,
        nullable=True
    )

    zones_visited = Column(
        JSON,
        nullable=True
    )

    total_dwell_ms = Column(
        Integer,
        default=0
    )

    converted = Column(
        Boolean,
        default=False,
        nullable=False
    )

    is_reentry = Column(
        Boolean,
        default=False,
        nullable=False
    )

    conversions = relationship(
        "ConversionRecord",
        back_populates="session",
        cascade="all, delete-orphan"
    )

    __table_args__ = (
        Index("idx_session_store", "store_id"),
        Index("idx_session_visitor", "visitor_id"),
    )


class ConversionRecord(Base):
    """
    Conversion tracking table.

    Stores purchase conversion information
    matched to visitor sessions.
    """

    __tablename__ = "conversion_records"

    conversion_id = Column(
        String,
        primary_key=True,
        nullable=False
    )

    session_id = Column(
        String,
        ForeignKey("visitor_sessions.session_id"),
        nullable=False,
        index=True
    )

    store_id = Column(
        String,
        nullable=False,
        index=True
    )

    transaction_id = Column(
        String,
        nullable=True
    )

    transaction_time = Column(
        DateTime,
        nullable=True
    )

    transaction_amount = Column(
        Float,
        nullable=True
    )

    matched = Column(
        Boolean,
        default=False,
        nullable=False
    )

    session = relationship(
        "VisitorSession",
        back_populates="conversions"
    )

    __table_args__ = (
        Index("idx_conversion_store", "store_id"),
        Index("idx_conversion_session", "session_id"),
    )